name: SGuser
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cycler=0.10.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.0
  - icu=68.1
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.1.0
  - libdeflate=1.7
  - libffi=3.3
  - libglib=2.68.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - matplotlib-base=3.4.2
  - mkl=2021.2.0
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.1.2
  - pixman=0.40.0
  - pycairo=1.20.1
  - pyparsing=2.4.7
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - rdkit=2021.03.3
  - readline=8.1
  - reportlab=3.5.67
  - setuptools=49.6.0
  - six=1.16.0
  - sqlalchemy=1.4.18
  - sqlite=3.35.5
  - tbb=2021.2.0
  - tk=8.6.10
  - torchaudio=0.4.0
  - torchvision=0.5.0
  - tornado=6.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==0.12.0
    - appnope==0.1.2
    - attrs==21.2.0
    - backcall==0.2.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==8.0.1
    - configargparse==1.4.1
    - decorator==4.4.2
    - flask==1.1.2
    - future==0.18.2
    - google-auth==1.31.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.0
    - idna==2.10
    - iniconfig==1.1.1
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - itsdangerous==2.0.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - loguru==0.5.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - networkx==2.5.1
    - oauthlib==3.1.1
    - opennmt-py==2.1.2
    - packaging==20.9
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - prompt-toolkit==3.0.18
    - protobuf==3.17.3
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.9.0
    - pyonmttok==1.26.2
    - pytest==6.2.4
    - pyyaml==5.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scaffoldgraph==1.1.1
    - scipy==1.6.3
    - selfies==1.0.4
    - sentencepiece==0.1.95
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - toml==0.10.2
    - torch==1.6.0
    - torchtext==0.5.0
    - tqdm==4.61.0
    - traitlets==5.0.5
    - urllib3==1.26.5
    - waitress==1.4.4
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - xlsxwriter==1.4.3
